shop_jewerly/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', add_product_to_cart, name='add_product_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('', cart_detail, name='cart_detail'),
]

shop_jewerly/main/urls.py
from django.urls import path, re_path
from .views import *


urlpatterns = [
    path('', main_page, name='home'),
    path('catalog', catalog_page, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', catalog_page, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),
    path('login', login_page, name='login'),
    path('logout', logout_page, name='logout'),
    path('sign_up', sign_up, name='sign_up'),
    path('profile', profile, name='profile'),
]

shop_jewerly/shop_jewerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('', include('main.urls'))
]

#for the server can access the user's files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_jewerly/main/models.py
from django.db import models
from django.urls import reverse
from rest_framework import serializers
#from django.core.urlresolvers import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id, self.slug])

    # def update_stock(self, product, count):
    #     product.stock -= count

shop_jewerly/orders/models.py
from django.db import models
from main.models import Product

# Create your models here.


class Order(models.Model):
    user_name = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def total_price(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop_jewerly/main/forms.py
from django.forms import Form, ModelForm, TextInput, CharField, EmailInput, PasswordInput, ValidationError
from django.contrib.auth.models import User as DjangoUser


class LoginForm(Form):
    username = CharField(label="Username")
    password = CharField(label="Password", widget=PasswordInput())


    class Meta:
        model = DjangoUser
        fields = ['username', 'password']

    def clean(self):
        data = self.cleaned_data
        if 'username' not in data and 'password' not in data:
            raise ValidationError("Please enter correct data")
        return data


class UserForm(ModelForm):
    username = CharField(label="Username")
    email = CharField(label="Email", widget=EmailInput())
    password = CharField(label="Password", widget=PasswordInput())

    class Meta:
        model = DjangoUser
        fields = ['username', 'email', 'password']

    def clean_password(self):
        if self.data['password']:
            _user = DjangoUser()
            _user.set_password(self.data['password'])
            return _user.password
        else:
            raise ValidationError("Don't understand You")

shop_jewerly/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as DjangoUser
from .forms import LoginForm, UserForm
from django.contrib.auth import logout, login
from django.contrib.auth import authenticate
from .models import Category, Product
from cart.forms import CartForm
from django.conf import settings

# Create your views here.


def main_page(request):
    return render(request, 'main/main_page.html')


def logout_page(request):
    logout(request)
    return redirect('home')


def login_page(request):
    error = ''

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                return redirect('login')
        else:
            error = 'ERROR!'
    else:
        form = LoginForm()
    return render(request, 'main/login_page.html', {
        'form': form,
        'error': error,
    })


def sign_up(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserForm()
    return render(request, 'main/sign_up.html', {'form': form})


@login_required()
def profile(request):
    user = request.user
    if user.is_authenticated:
        user_name = user
        email = request.user.email
    return render(request, 'main/profile.html',
                  {'user_name': user_name, 'email': email, })


def catalog_page(request, category_slug=None): #products list
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    # добавить фильтрацию на кол-во: если 0 -
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'main/catalog.html',
                 {'category': category,
                  'categories': categories,
                  'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartForm()
    return render(request, 'main/product_detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

shop_jewerly/main/templates/main/catalog.html
{% extends "main/index_page.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}All{% endif %}
{% endblock title%}

{% block content %}
<section class="main-section" id="service">
<div class="container">
    <h2>Catalog</h2>
    <h6>Best jewelry for you.</h6>
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %} >
                <a href="/catalog" >All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}All{% endif %}</h1>
        {% for product in products %}
            <div class="item" style="float:left; margin: 10px 10px 10px 10px;">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_img.png' %}{% endif %}">
                </a>
                <div class="product-list">
                    <a href="{{ product.get_absolute_url }}" class="product">{{ product.name }}</a>
                    <br>
                    <span class="price">${{ product.price }}</span>
                </div>
            </div>
        {% endfor %}
    </div>

<!--<section class="main-section paddind" id="Portfolio">-->
<!--		<div class="container">-->
<!--			<h2>Catalog</h2>-->
<!--			<h6>Best jewelry for you.</h6>-->
<!--            <h3 style="text-align: center;">Categories</h3>-->
<!--			<div class="portfolioFilter">-->
<!--				<ul class="Portfolio-nav wow fadeIn delay-02s">-->
<!--					<li {% if not category %}class="selected"{% endif %} >-->
<!--                        <a href="/catalog" >All</a>-->
<!--                    </li>-->

<!--                    {% for c in categories %}-->
<!--                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>-->
<!--                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>-->
<!--                    </li>-->
<!--                    {% endfor %}-->
<!--				</ul>-->
<!--			</div>-->


<!--            <div class="portfolioContainer wow fadeInUp delay-04s">-->
<!--                <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>-->
<!--                    {% for product in products %}-->
<!--                    <div class=" Portfolio-box printdesign">-->
<!--                        <a href="{{ product.get_absolute_url }}">-->
<!--                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_img.png' %}{% endif %}">-->
<!--                        </a>-->
<!--                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>-->
<!--                        ${{ product.price }}-->
<!--                    {% endfor %}-->
<!--                    </div>-->
<!--            </div>-->
<!--        </div>-->
<!--</section>-->
</div>
</section>
{% endblock content %}

shop_jewerly/main/templates/main/index_page.html
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, maximum-scale=1">


	<title>{% block title %}Jewerly{% endblock %}</title>

	{% load static %}
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png">
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="img/x-icon">

	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'>

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/base.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.1.8.3.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-scrolltofixed.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.isotope.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/wow.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/classie.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/magnific-popup.js' %}"></script>
	<script src="{% static 'contactform/contactform.js' %}"></script>

</head>

<body>

	<nav class="main-nav-outer" id="test">
		<div class="container">
			<ul class="main-nav">
				<li><a href="/">Home</a></li>
				<li><a href="/catalog">Catalog</a></li>
				<li><a href="/#contact">Contact</a></li>
				<li class="small-logo"><a href="#header"><img src="{% static 'img/newlogo.png' %}" alt=""></a></li>
				{% if user.is_authenticated %}
				<li><a href="/profile">Profile</a></li>
				<li><a href="/logout">LogOut</a></li>
				{% else %}
				<li><a href="/sign_up">SignUp</a></li>
				<li><a href="/login">LogIn</a></li>
				{% endif %}
				<li>
		        {% with total_items=cart|length %}
        		{% if cart|length > 0 %}
        		<a href="{% url 'cart:cart_detail' %}">
            	Your cart
				</a>
						{% else %}
						Your cart is empty.
						{% endif %}
						{% endwith %}
				</li>
			</ul>
			<a class="res-nav_click" href="#"><i class="fa fa-bars"></i></a>
		</div>
	</nav>

	{% if messages%}
		{% for message in messages%}
			<div class="alert-success">
				{{message}}
			</div>
		{% endfor %}
	{% endif %}

	{% block content %} {% endblock content %}
	<script type="text/javascript">
		$(document).ready(function(e) {

			$('#test').scrollToFixed();
			$('.res-nav_click').click(function() {
				$('.main-nav').slideToggle();
				return false

			});

      $('.Portfolio-box').magnificPopup({
        delegate: 'a',
        type: 'image'
      });

		});
	</script>

	<script>
		wow = new WOW({
			animateClass: 'animated',
			offset: 100
		});
		wow.init();
	</script>


	<script type="text/javascript">
		$(window).load(function() {

			$('.main-nav li a, .servicelink').bind('click', function(event) {
				var $anchor = $(this);

				$('html, body').stop().animate({
					scrollTop: $($anchor.attr('href')).offset().top - 102
				}, 1500, 'easeInOutExpo');
				/*
				if you don't want to use the easing effects:
				$('html, body').stop().animate({
					scrollTop: $($anchor.attr('href')).offset().top
				}, 1000);
				*/
				if ($(window).width() < 768) {
					$('.main-nav').hide();
				}
				event.preventDefault();
			});
		})
	</script>

	<script type="text/javascript">
		$(window).load(function() {


			var $container = $('.portfolioContainer'),
				$body = $('body'),
				colW = 375,
				columns = null;


			$container.isotope({
				// disable window resizing
				resizable: true,
				masonry: {
					columnWidth: colW
				}
			});

			$(window).smartresize(function() {
				// check if columns has changed
				var currentColumns = Math.floor(($body.width() - 30) / colW);
				if (currentColumns !== columns) {
					// set new column count
					columns = currentColumns;
					// apply width to container manually, then trigger relayout
					$container.width(columns * colW)
						.isotope('reLayout');
				}

			}).smartresize(); // trigger resize to set container width
			$('.portfolioFilter a').click(function() {
				$('.portfolioFilter .current').removeClass('current');
				$(this).addClass('current');

				var selector = $(this).attr('data-filter');
				$container.isotope({

					filter: selector,
				});
				return false;
			});

		});
	</script>
</body>
</html>

shop_jewerly/main/templates/main/login_page.html
{% extends "main/index_page.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="container" style="margin-top: 5%;text-align: center">
    <div class="form-section">
        <h3 style="text-align: center">Log into your account</h3>
        <br>
        <form method = "post">
            {%if error%}<b>{{error}} </b>{%endif%}
            {% csrf_token %}
            {{form}}
            <br />
            <br />
            <button type="Submit" class="btn btn-outline-warning">Login</button>
        </form>
        <hr>
        No profile yet? <a href="/login">Sign up</a>
    </div>
</div>
{% endblock content %}

shop_jewerly/main/templates/main/main_page.html
{% extends "main/index_page.html" %}
{% load static %}

{% block title %}
	<title>My shop</title>
{% endblock title %}

{% block content %}
	<section class="main-section" id="service">
		<!--main-section-start-->
		<div class="container">
			<h2>Jewerly</h2>
			<h6>We offer a large jewelry selection of unique design.</h6>
			<div class="row">
				<div class="col-lg-4 col-sm-6 wow fadeInLeft delay-05s">
					<div class="service-list">
						<div class="service-list-col1">
							<i class="fa fa-heart"></i>
						</div>
						<div class="service-list-col2">
							<h3>branding &amp; identity</h3>
							<p>Compare our pearls head-to-head against ANY luxury brand. You will not find better quality and price.</p>
						</div>
					</div>
					<div class="service-list">
						<div class="service-list-col1">
							<i class="fa fa-diamond"></i>
						</div>
						<div class="service-list-col2">
							<h3>100% quality</h3>
							<p>We select pearls of the best quality especially for our customers, investing our soul and strength.</p>
						</div>
					</div>
					<div class="service-list">
						<div class="service-list-col1">
							<i class="fa fa-eye"></i>
						</div>
						<div class="service-list-col2">
							<h3>Original design</h3>
							<p>The design of each of our jewelry is created with a special approach. Therefore, our dyes are sold in a limited copy.</p>
						</div>
					</div>
					<div class="service-list">
						<div class="service-list-col1">
							<i class="fa fa-handshake-o"></i>
						</div>
						<div class="service-list-col2">
							<h3>Return policy</h3>
							<p>Every order comes with our 100-day "no hassle" return policy. </p>
						</div>
					</div>
				</div>
				<figure class="col-lg-8 col-sm-6  text-right wow fadeInUp delay-02s">
					<img src="{% static 'img/jewelry.png' %}" alt="">
				</figure>

			</div>
		</div>
	</section>
	<!--main-section-end-->

	<section class="business-talking">
		<!--business-talking-start-->
		<div class="container">
			<h2>Our contacts</h2>
		</div>
	</section>
	<!--business-talking-end-->
	<div class="container">
		<section class="main-section contact" id="contact">

			<div class="row">
				<div class="col-lg-6 col-sm-7 wow fadeInLeft">
					<div class="contact-info-box address clearfix">
						<h3><i class=" icon-map-marker"></i>Address:</h3>
						<span>308 Negra Arroyo Lane<br>Albuquerque, New Mexico, 87111.</span>
					</div>
					<div class="contact-info-box phone clearfix">
						<h3><i class="fa fa-phone"></i>Phone:</h3>
						<span>1-800-BOO-YAHH</span>
					</div>
					<div class="contact-info-box email clearfix">
						<h3><i class="fa fa-pencil"></i>email:</h3>
						<span>hello@knightstudios.com</span>
					</div>
					<div class="contact-info-box hours clearfix">
						<h3><i class="fa fa-clock-o"></i>Hours:</h3>
						<span><strong>Monday - Thursday:</strong> 10am - 6pm<br><strong>Friday:</strong> People work on Fridays now?<br><strong>Saturday - Sunday:</strong> Best not to ask.</span>
					</div>
					<ul class="social-link">
						<li class="twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li class="pinterest"><a href="#"><i class="fa fa-pinterest"></i></a></li>
						<li class="gplus"><a href="#"><i class="fa fa-google-plus"></i></a></li>
						<li class="dribbble"><a href="#"><i class="fa fa-dribbble"></i></a></li>
					</ul>
				</div>
<!--				<div class="col-lg-6 col-sm-5 wow fadeInUp delay-05s">-->
<!--					<div class="form">-->

<!--						<div id="sendmessage">Your message has been sent. Thank you!</div>-->
<!--						<div id="errormessage"></div>-->
<!--						<form action="" method="post" role="form" class="contactForm">-->
<!--							<div class="form-group">-->
<!--								<input type="text" name="name" class="form-control input-text" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />-->
<!--								<div class="validation"></div>-->
<!--							</div>-->
<!--							<div class="form-group">-->
<!--								<input type="email" class="form-control input-text" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />-->
<!--								<div class="validation"></div>-->
<!--							</div>-->
<!--							<div class="form-group">-->
<!--								<input type="text" class="form-control input-text" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />-->
<!--								<div class="validation"></div>-->
<!--							</div>-->
<!--							<div class="form-group">-->
<!--								<textarea class="form-control input-text text-area" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>-->
<!--								<div class="validation"></div>-->
<!--							</div>-->

<!--							<div class="text-center"><button type="submit" class="input-btn">Send Message</button></div>-->
<!--						</form>-->
<!--					</div>-->
<!--				</div>-->
			</div>
		</section>
	</div>
	<footer class="footer">
		<div class="container">
			<div class="footer-logo"><a href="#"><img src="{% static 'img/logo1.png' %}" alt=""></a></div>
			<span class="copyright">&copy; Knight Theme. All Rights Reserved</span>
			<div class="credits">
				<!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Knight
        -->
				Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
			</div>
		</div>
	</footer>

{% endblock content%}

shop_jewerly/main/templates/main/product_detail.html
{% extends "main/index_page.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
             style="float: left;margin: 17px 17px 17px 7px;">
        <h1>{{ product.name }}</h1>
        <hr>
        <h3><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
        <p class="price">${{ product.price }}</p>
            <form action="{% url 'cart:add_product_to_cart' product.id %}" method="post">
                {{cart_product_form}}
                {% csrf_token %}
                <input type="submit" value="Add to cart">
            </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop_jewerly/main/templates/main/profile.html
{% extends "main/index_page.html" %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="container" style="margin-top: 5%;text-align: center">
    <div class="form-section">
        <h3 style="text-align: center">My profile</h3>
        <br>
        <form method="post" name="form">
                {% csrf_token %}
                <p><label for="id_user">Name:</label>
                <input type="text" name="user_name" id="id_user"  value={{user_name}} readonly></p>

                <p><label for="id_email">Email:</label>
                <input type="email" name="email" id="id_email"  value={{email}} readonly></p>

                <hr>
                <a href="/cart">View my cart</a>
        </form>
    </div>
</div>
{% endblock %}

shop_jewerly/main/templates/main/sign_up.html
{% extends "main/index_page.html" %}
{% block title %}SignUp{% endblock %}

{% block content %}
<div class="container" style="margin-top: 5%;">
    <div class="form-section">
        <h3 style="text-align: center">Create an account</h3>
        <br>
        <form method="post" name="form">
                {% csrf_token %}
                {{ form.as_div }}
            <br />
            <button type="submit" class="btn btn-outline-warning">Sign up</button>
        </form>
        <hr>
        Already registered? <a href="/login">Login</a>
    </div>
</div>
{% endblock %}