shop_jewerly/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', add_product_to_cart, name='add_product_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('', cart_detail, name='cart_detail'),
]

shop_jewerly/orders/urls.py
from django.urls import re_path
from . import views

app_name = "orders"

urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
]

shop_jewerly/shop_jewerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('', include('main.urls'))
]

#for the server can access the user's files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_jewerly/orders/models.py
from django.db import models
from main.models import Product

# Create your models here.


class Order(models.Model):
    user_name = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def total_price(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop_jewerly/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user_name', 'email', 'address']

shop_jewerly/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderForm
from cart.cart import Cart
from .tasks import new_order
from main.models import Product

from django.shortcuts import get_object_or_404

# Create your views here.


def order_create(request):
    cart = Cart(request)

    user = request.user
    user_name = ''
    email = ''

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                product = Product.objects.get(name=item['product'])
                count = product.stock - item['quantity']
                #print(count)
                Product.objects.filter(name=item['product']).update(stock=count)
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear_cart()
            new_order.delay(order.id)
            return render(request, 'orders/created_order.html',
                          {'order': order,})
    else:
        form = OrderForm
        if user.is_authenticated:
            user_name = user
            email = request.user.email
    return render(request, 'orders/order_create.html',
                  {'cart': cart, 'user_name': user_name, 'email': email, 'form': form})

shop_jewerly/orders/templates/orders/created_order.html
{% extends "main/main_page.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<div class="container" style="margin-top: 5%;text-align: center">
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
</div>
{% endblock %}

shop_jewerly/orders/templates/orders/order_create.html
{% extends "main/main_page.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container" style="margin-top: 5%;text-align: left">
    <h1>Checkout</h1>
    <br />
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {%if user and email%}
            <p><label for="id_user">Name:</label>
            <input type="text" name="user_name" id="id_user"  value={{user}}></p>

            <p><label for="id_email">Email:</label>
            <input type="email" name="email" id="id_email"  value={{email}}></p>

            <p><label for="id_address">Address:</label>
            <input type="text" name="address" id="id_address" required></p>
        {%else%}
            {{ form.as_p }}
        {%endif%}
        <br />
        <p><input type="submit" class="btn btn-outline-warning" value="Place order"></p>
        {% csrf_token %}
    </form>
</div>
{% endblock %}