shop_jewerly/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', add_product_to_cart, name='add_product_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('', cart_detail, name='cart_detail'),
]

shop_jewerly/orders/urls.py
from django.urls import re_path
from . import views

app_name = "orders"

urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
]

shop_jewerly/shop_jewerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('', include('main.urls'))
]

#for the server can access the user's files
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_jewerly/cart/models.py
from django.db import models

# Create your models here.

shop_jewerly/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]


class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop_jewerly/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .forms import CartForm
from .cart import Cart
from main.models import Product
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.

@require_POST
def add_product_to_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        available_count = data['quantity']
        if available_count <= product.stock:
            cart.add_to_cart(product=product,
                             quantity=data['quantity'],
                             update=data['update'])
            return redirect('cart:cart_detail')
        else:
            messages.error(request, 'Sorry, this jewelry is not available in this quantity.')
    return redirect('cart:cart_detail')


def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.delete_from_cart(product)
    return redirect('cart:cart_detail')


#the cart status
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartForm(initial={'quantity': item['quantity'],
                                                         'update': True})
    return render(request, 'cart/details.html', {'cart': cart})

shop_jewerly/cart/templates/cart/details.html
{% extends "main/main_page.html" %}
{% load static %}
{% block title %}Shopping cart{% endblock %}

{% block content %}
<div class="container">
    <h1>Your shopping cart</h1>
    <table class="cart">
<!--        <thead>-->
<!--        <tr>-->
<!--            <th>Image</th>-->
<!--            <th>Product</th>-->
<!--            <th>Change count</th>-->
<!--            <th>Remove</th>-->
<!--            <th>Count</th>-->
<!--            <th>Unit price</th>-->
<!--            <th>Price</th>-->
<!--        </tr>-->
<!--        </thead>-->

        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                      <form action="{% url 'cart:add_product_to_cart' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                      </form>
                    </td>
                    <td><a href="{% url 'cart:remove_from_cart' product.id%}">Remove</a></td>
                    <td>{{ item.quantity }}</td>
                    <td class="num">${{ item.price }}</td>
<!--                    <td class="num">${{ item.total_price }}</td>-->
                </tr>
            {% endwith %}
        {% endfor %}

        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_price }}</td>
        </tr>
        </tbody>
    </table>
    <hr>
    <p class="text-right" >
        <big><big>
       <a href="{% url 'orders:order_create' %}"> Checkout</a>
        </big></big>
    </p>
</div>
{% endblock %}